name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_on_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: make

  build_on_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make
